version: '3'
services:
  app:
    container_name: goapp
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./go/src/work:/go/src/work
